#!/usr/bin/env python3
"""Derive and freeze the three pools from PROTOCOL.md section 2.

Run once; the manifests it writes are committed and are what every later stage
reads. Re-running must reproduce them byte for byte.

Usage:
    ./pools.py            # derive, validate against section 2, write manifests
    ./pools.py --check    # validate only, write nothing
"""

import argparse
import hashlib
import json
import os
import sys

import numpy as np

import protocol as P

POOL_DIR = "pools"


def _rng(seed):
    return np.random.default_rng(seed)


def permutation_for(item_id):
    """This item's option order: stable per item, independent of pool membership.

    Section 4 requires one permutation per item applied identically to every
    arm including J. Deriving it from a hash of the id rather than from a
    sequential draw means an item's order does not depend on how many items
    were drawn before it, so the order survives any change in pool ordering.
    """
    digest = hashlib.sha256(
        f"{P.SEEDS['shuffle']}:{item_id}".encode("utf-8")).digest()
    seed = int.from_bytes(digest[:8], "big")
    order = _rng(seed).permutation(P.K)
    return [P.LABELS[i] for i in order]


def to_shuffled(vec, options):
    """Canonical-order vector -> this item's shuffled option order."""
    idx = [P.LABELS.index(o) for o in options]
    return np.asarray(vec, dtype=float)[idx]


def to_canonical(vec, options):
    """Shuffled-order vector -> canonical LABELS order."""
    out = np.empty(P.K, dtype=float)
    for pos, opt in enumerate(options):
        out[P.LABELS.index(opt)] = vec[pos]
    return out


def _item(row):
    return {
        "id": row["id"],
        "label": row["primary_category"],
        "published": row["published"],
        "title": row["title"],
        "abstract": row["abstract"],
        "options": permutation_for(row["id"]),
    }


def derive_pools(rows):
    """Split in-set rows into evaluation, dev and anchor pools.

    Order matters and is fixed by section 2: the evaluation sample is drawn
    from post-start papers, then the dev sample from pre-start papers, then
    the anchor pool is every pre-start paper the dev draw did not take.
    """
    post = sorted((r for r in rows if r["published"][:10] >= P.START_DATE),
                  key=lambda r: r["id"])
    pre = sorted((r for r in rows if r["published"][:10] < P.START_DATE),
                 key=lambda r: r["id"])

    if len(rows) != P.EXPECTED["in_set"]:
        raise SystemExit(
            f"STOP: in-set count is {len(rows)}, protocol section 2 says "
            f"{P.EXPECTED['in_set']}. The filter disagrees with the "
            f"pre-registration; investigate before running anything.")
    if len(post) != P.EXPECTED["post_start"]:
        raise SystemExit(
            f"STOP: post-start count is {len(post)}, protocol says "
            f"{P.EXPECTED['post_start']}.")

    eval_idx = _rng(P.SEEDS["evaluation"]).choice(
        len(post), size=P.POOL_SIZES["evaluation"], replace=False)
    evaluation = [post[i] for i in sorted(eval_idx)]

    dev_idx = _rng(P.SEEDS["dev"]).choice(
        len(pre), size=P.POOL_SIZES["dev"], replace=False)
    dev_ids = {pre[i]["id"] for i in dev_idx}
    dev = [pre[i] for i in sorted(dev_idx)]
    anchor = [r for r in pre if r["id"] not in dev_ids]

    if len(anchor) != P.EXPECTED["anchor"]:
        raise SystemExit(
            f"STOP: anchor count is {len(anchor)}, protocol says "
            f"{P.EXPECTED['anchor']}.")

    return {name: [_item(r) for r in pool] for name, pool in
            (("evaluation", evaluation), ("dev", dev), ("anchor", anchor))}


def load_pool(name):
    path = os.path.join(POOL_DIR, f"{name}.jsonl")
    with open(path, encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def _write(pools_by_name):
    os.makedirs(POOL_DIR, exist_ok=True)
    for name, items in pools_by_name.items():
        with open(os.path.join(POOL_DIR, f"{name}.jsonl"), "w",
                  encoding="utf-8") as fh:
            for it in items:
                fh.write(json.dumps(it, ensure_ascii=False, sort_keys=True) + "\n")


def _counts_md(pools_by_name, report):
    from collections import Counter
    lines = ["# Derived pool counts", "",
             "Generated by `pools.py`. Every number here is recomputed from "
             "`arxiv_last_30_days.csv`, whose SHA-256 is checked on load.", "",
             "| Pool | Count | Protocol section 2 |", "| --- | --- | --- |"]
    for name, expected in (("evaluation", 2000), ("dev", 200),
                           ("anchor", P.EXPECTED["anchor"])):
        lines.append(f"| {name} | {len(pools_by_name[name])} | {expected} |")
    lines += ["", "## Realized evaluation class counts", "",
              "Section 2's per-class numbers are expectations from the "
              "post-start pool proportions and are marked \"(rounded)\"; "
              "realized draws differ by a few items.", "",
              "| Label | Realized | Expected |", "| --- | --- | --- |"]
    c = Counter(r["label"] for r in pools_by_name["evaluation"])
    exp = {"cs.CV": 442, "cs.LG": 429, "cs.AI": 343, "cs.RO": 292,
           "cs.CL": 291, "cs.CR": 160, "cs.IR": 44}
    for label in P.LABELS:
        lines.append(f"| {label} | {c[label]} | {exp[label]} |")
    lines += ["", "## Integrity", "",
              f"- rows: {report['n']}",
              f"- duplicate ids: {report['duplicate_ids']}",
              f"- abstracts under 100 chars: {report['short_abstracts']}",
              f"- abstract words, median: {report['median_words']}, "
              f"p95: {report['p95_words']}", ""]
    lines += ["", "## Provenance and reproducibility", "",
              f"- numpy: {np.__version__} (pinned in `requirements.txt`)",
              f"- source CSV SHA-256: `{P.CSV_SHA256}`",
              f"- seeds: evaluation {P.SEEDS['evaluation']}, dev {P.SEEDS['dev']}, "
              f"option shuffle {P.SEEDS['shuffle']}",
              "",
              "The committed `pools/*.jsonl` manifests are the authoritative record. "
              "Re-running `pools.py` reproduces them byte-for-byte under the pinned "
              "numpy version; numpy guarantees a stable stream per BitGenerator and "
              "seed, but not that `Generator` method output is identical across "
              "versions, so a different numpy may derive a different sample from the "
              "same seeds. The manifests, not the derivation, are what the "
              "pre-registration is checked against.",
              ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="validate only; write nothing")
    args = ap.parse_args()

    rows = P.in_set(P.load_rows())
    report = P.integrity_report(rows)
    pools_by_name = derive_pools(rows)

    for name, items in pools_by_name.items():
        print(f"  {name:11} {len(items):5}", file=sys.stderr)

    if args.check:
        print("check passed; nothing written", file=sys.stderr)
        return
    _write(pools_by_name)
    with open(os.path.join(POOL_DIR, "counts.md"), "w", encoding="utf-8") as fh:
        fh.write(_counts_md(pools_by_name, report))
    print(f"wrote manifests to {POOL_DIR}/", file=sys.stderr)


if __name__ == "__main__":
    main()
